#!/bin/bash
PID=$(ps -e|grep parsedata |grep -v grep| awk '{printf $1}')

if [ -n "$PID" ]; then
echo "process running"
exit
else
sudo /home/top-down/workspace/MySqlAduitSystem/code/new_parse_dir/parsedata
fi

