main2:server.cpp WebRender.cpp ../code/public_dir/ASDB.c
	g++ $^ -o $@ -std=c++11 -lpthread -L ~/workspace/lib/ThirdPartLibForCpp/el7.x86_64/third_part/lib/ \
	-lctemplate -I ~/workspace/lib/ThirdPartLibForCpp/el7.x86_64/third_part/include/ \
	-I/usr/include/mysql -L/usr/lib64/mysql -lmysqlclient
